#!/bin/bash
source /home/ec2-user/.bash_profile
export PATH=$PATH:/home/ec2-user/.nvm/versions/node/v14.15.0/bin/
export HOME=/home/ec2-user

if [ "$DEPLOYMENT_GROUP_NAME" == "frontend-servers" ]
then
    sudo service httpd start
else
    pm2 start /home/ec2-user/marshallamey.com/server/server.js --name marshallamey.com
fi